### ISSUE TITLE
Returns error for status 

### ISSUE THREAD

**Issue by OlgaLebed** [vandaref/from_notion_to_habitica#1]
The code returns an error for status even though it's set up properly
![Screenshot 2024-02-04 160118](https://github.com/vandaref/from_notion_to_habitica/assets/48255929/19706348-6640-44c7-bfe7-f4e3c968d150)

==========================
Reading data
==========================
Reading Notion Data
200
Reading Habitica Data
200
Reading Habitica Done Data
200
==========================
Syncing Notion to Habitica
==========================
Traceback (most recent call last):
  File "from_notion_to_habitica.py", line 206, in <module>
    syncNotionToHabitica()
  File "from_notion_to_habitica.py", line 153, in syncNotionToHabitica
    notionDoneList = getDoneListOfNotion()
  File "from_notion_to_habitica.py", line 133, in getDoneListOfNotion
    return getNotionList(notionDoneCondn)
  File "from_notion_to_habitica.py", line 112, in getNotionList
    status = i['properties']['Status']['select']['name']
KeyError: 'select'

**Comment by vandaref** [comment]
Could you share your json from notion ?

**Comment by vandaref** [comment]
Could you share your json from notion ?

**Comment by OlgaLebed** [comment]
Hey, I think it's a specific issue with the Notion "tasks" template where "Status" is a special property. It only occurred to me after opening up the issue. But here is the json if you're curious
[notion.json](https://github.com/vandaref/from_notion_to_habitica/files/14170838/notion.json)

**Comment by vandaref** [comment]
Problem is here : **"type": "status", "status"**
Your property status has type **status** instead of **select**

**Comment by OlgaLebed** [comment]
Yeah, notion tasks template database has a “Status” property that is separate from regular drop-down generic property. So the script doesn’t work for it. They also locked it so you can’t remove it which is a bummer
https://www.notion.so/templates/notion-projects-and-tasks

**Comment by vandaref** [comment]
You can try to edit the code from :
```
for i in data['results']:
        name = i['properties']['Name']['title'][0]['text']['content']
        status = i['properties']['Status']['select']['name']
        priority = i['properties']['Priority']['select']['name']
```
        
to :
```
for i in data['results']:
        name = i['properties']['Name']['title'][0]['text']['content']
        status = i['properties']['Status']['status']['name']
        priority = i['properties']['Priority']['select']['name']
```

**Comment by vandaref** [comment]
![image](https://github.com/vandaref/from_notion_to_habitica/assets/124267967/43171d82-3f46-4212-8ae2-50fdca2ca554)
![image](https://github.com/vandaref/from_notion_to_habitica/assets/124267967/457d1ea4-6145-4b88-ae92-d917f3f30cf7)

**Comment by vandaref** [comment]
> You can try to edit the code from :
> 
> ```
> for i in data['results']:
>         name = i['properties']['Name']['title'][0]['text']['content']
>         status = i['properties']['Status']['select']['name']
>         priority = i['properties']['Priority']['select']['name']
> ```
> 
> to :
> 
> ```
> for i in data['results']:
>         name = i['properties']['Name']['title'][0]['text']['content']
>         status = i['properties']['Status']['status']['name']
>         priority = i['properties']['Priority']['select']['name']
> ```

Here also :
def scoreTaskInNotion(name, headers):
    url = f"https://api.notion.com/v1/pages/{name}"
    res = requests.patch(url, headers=headers, json={"properties": {"Status" : {"status" :{"name": completed()}}}})
    data = res.json()
    #print(res.text)
    print(res.status_code)

**Comment by OlgaLebed** [comment]
It worked! Thank you!

**Comment by vandaref** [comment]
> It worked! Thank you!

Great ! Good to know. 
Don’t hesitate to leave a star if you’re satisfied ;)

**Comment by vandaref** [comment]
I close the issue
